### PR TITLE
Fixes #26

### LINKED ISSUE #26: Chapter 2 subsec colorbars example data missing
Seems like the example data used in chapter 2 at the colorbar example is no longer supported as of py 3.1. bivariate_normal.npy is not in any folder and has apparantly been discontinued.

### PR DESCRIPTION
**Pull request by ggodreau**
- /mpl-data/sample_data/axes_grid folder appears to no longer exists as of matplotlib v2.2.2
  - added /assets folder in repo containing dependent numpy pickle, 'bivariate_normal.npy' file
  - revised load of data in AnatomyOfMatplotlib-Part2-Plotting_Methods_Overview.ipynb to reflect this change
  - tested successfully with matplotlib v2.2.2 and python v3.6.6

### CODE REVIEW

**Comment by choldgraf** [comment]
This seems reasonable to me! Anybody have objections to including this data w/ the repo?

**Comment by ggodreau** [comment]
@choldgraf I considered pulling it down from GH or a CDN but I:

- didn't want to have an additional post-clone network dependency (and library import)
- didn't want to deal with 'where to install' the file (possible multiple paths and local file system permissions issues)

So I decided it'd be easier and more reliable to include the file in the repo. T'was my raison d'etre :tokyo_tower:  :wine_glass:

**Comment by timhoffm** [comment]
Not sure why sample data is not available. Maybe, because technically it's an optional package.

OTOH adding a 1.8k file to this repo is not that bad either.

**Comment by WeatherGod** [comment]
I am a little embarrassed that I didn't think of this before. Of course, I didn't ever spend much time thinking about it because I always assumed that the sample data will always be packaged with matplotlib... This seems totally reasonable.

**Pull request merged**
